### ISSUE TITLE
lib import issues

### ISSUE THREAD

**Issue by zaiweizhang** [chrischoy/SpatioTemporalSegmentation#42]
Hi,

I have one problem with the lib import issues:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/home/zaiweizhang/ssl_scaling/third-party/SpatioTemporalSegmentation/lib/datasets/__init__.py", line 1, in <module>
    import lib.datasets.synthia as synthia
ModuleNotFoundError: No module named 'lib'

It's keep giving me this issue, and using python -m main doesn't work.

**Comment by zaiweizhang** [comment]
fixed

**Comment by shivani33** [comment]
Hello,
I am having the same issue when preprecessing the standford dataset. Could you please decribe the solution that worked for you?Thank you in advance.
